### PR TITLE
added OpenBrowser task

### PR DESCRIPTION
**Pull request by oscarotero**
This task allows to open a web browser with one or more urls. (#225)

```php
//open one url
$this->taskOpenBrowser('http://robo.li')->run();

//open more urls:
$this->taskOpenBrowser([
    'http://robo.li',
    'https://github.com/Codegyre/Robo'
])->run();
```

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks!

**Comment by oscarotero** [comment]
no problem :smile:

**Comment by DavertMik** [comment]
I'm working to release 0.6.0 so this task will be included

**Comment by oscarotero** [comment]
Great news :+1:

**Pull request merged**
