### PR TITLE
Added gulp task

### PR DESCRIPTION
**Pull request by schorsch3000**
#### What's this PR do?
it adds the taskGulpRun(), which runs gulp-tasks.
Yes, it looks like taskrunnerception, but there are projects split in frontend and backend and grunt / gulp are quite nice for frontend-task.
#### How should this be manually tested?
with something like:
```
public function gulptest($task='default'){

        $this->taskGulpRun();
        $this->taskGulpRun($task)->color()->simple()->run();
    }
```

### CODE REVIEW

**Comment by schorsch3000** [comment]
the travis-ci build breaks up on the q in 
"codeception/aspect-mock": "0.5q.*"
in composer.json which i fixed locally but did not commit

**Comment by DavertMik** [comment]
@schorsch3000 thanks! Especially for handling new task format!

**Comment by boedah** [comment]
In Run->run() you call Base->getCommand() with a parameter, but the method has none and uses $this->task directly.

**Comment by DavertMik** [comment]
@boedah thanks, fixed it

**Pull request merged**
