### PR TITLE
Update robo

### PR DESCRIPTION
**Pull request by Narno**
Cleaner method to detect if Robo is running from Phar file or not.

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks

**Comment by DavertMik** [comment]
But unfortunately it does not work this way :(

```
robo
PHP Fatal error:  Class 'Robo\Runner' not found in /usr/bin/robo on line 18
PHP Stack trace:
PHP   1. {main}() /usr/bin/robo:0

```

I reverted back this change

**Comment by DavertMik** [comment]
Unfortunately this does not work this way:

```
robo
PHP Fatal error:  Class 'Robo\Runner' not found in /usr/bin/robo on line 18
PHP Stack trace:
PHP   1. {main}() /usr/bin/robo:0

```

**Comment by Narno** [comment]
Arg, I'm doing more tests.

**Pull request merged**
