### PR TITLE
Split off trait CommandArguments from ExecOneCommand

### LINKED ISSUE #105: CommandStack and ExecOneCommand cannot be used at the same time (since ExecOneCommand defines same property ($finishedAt))
New in Robo 0.5.0 (also see #87).

Prereq:
Task which extends CommandStack and wants to use ExecOneCommand (for arg, args, options).

* CommandStack uses ExecCommand uses Timer
* ExecOneCommand uses ExecCommand uses Timer

```
ERROR: Robo\Task\CommandStack and Robo\Common\ExecOneCommand define the same property ($finishedAt) in the composit
ion of Boedah\Robo\Task\Drush\DrushStack. This might be incompatible, to improve maintainability consider using acc
essor methods in traits instead.
```

### PR DESCRIPTION
**Pull request by boedah**
To be able to use it stand-alone.

For details, see https://github.com/Codegyre/Robo/issues/105#issuecomment-71763526

fixes #105

### CODE REVIEW

**Comment by DavertMik** [comment]
Yes, this looks a really logical solution.

**Comment by boedah** [comment]
:+1: thanks!

**Comment by boedah** [comment]
@DavertMik would you mind doing a quick 0.5.2 release?
(Since this PR is blocking me from releasing a working robo-drush version for 0.5.x).

**Comment by boedah** [comment]
@DavertMik could you? ;)

**Pull request merged**
